version: "3.8"
services:
  db:
    container_name: CRUD_PRODUCTS
    image: postgres
    restart: always
    ports:
      - "5433:5432"
    volumes:
      - ./db-Data:/var/lib/postgresql/data
      - ./scripts/create_product_table.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres1234
      - POSTGRES_DB=crud_products

volumes:
  db:
    driver: bridge