version: '3'
services:
  product_api:
    build: .
    ports:
      - 4000:4000
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    environment:
      - APIPORT=4000
      - DBHOST=postgres_db
      - DBPORT=5432
      - DBUSER=postgres
      - DBPASS=postgres1234
      - DBNAME=crud_products

  postgres_db:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres1234
      - POSTGRES_DB=crud_products
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./postgres-data-base/scripts/create_product_table.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  pgdata: